version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      # Type the command to log in to your Docker Hub account here.
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # - docker build -t personal-entries .
      - docker-compose up -d
      - docker tag personal-entries:latest rafaelzulianeli/personal-entries:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push rafaelzulianeli/personal-entries:latest
